name: Dependency & Docker Image Scan

on:
  workflow_run:
    workflows: ["codeQL Analysis"]
    types:
      - completed

jobs:
  dependency-and-image-scan:
    name: Scan Dependencies & Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy -y

      - name: Scan Dependencies
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Scan Docker image
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL myapp:latest

      - name: Generate Trivy Reports
        run: |
          trivy fs --format json --output trivy-dependencies-report.json .
          trivy image --format json --output trivy-docker-report.json myapp:latest

      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-reports
          path: |
            trivy-dependencies-report.json
            trivy-docker-report.json
