name: CodeQL Analysis & Dependency/Image Scan

on:
  push:
  pull_request:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  analyze:
    name: Analyse statique (CodeQL)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['javascript', 'python']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: ./results

      # Convert SARIF to HTML without sarif-tools
      - name: Convert SARIF to HTML
        run: |
          python3 - <<'EOF'
          import json, sys
          from pathlib import Path
          sarif_file = Path("results/${{ matrix.language }}.sarif")
          if sarif_file.exists():
              data = json.loads(sarif_file.read_text())
              html_content = "<html><body><h1>CodeQL Report</h1>"
              for run in data.get("runs", []):
                  for result in run.get("results", []):
                      rule_id = result.get("ruleId", "N/A")
                      message = result.get("message", {}).get("text", "")
                      severity = next((tag for tag in result.get("properties", {}).get("tags", []) if "severity" in tag.lower()), "Unknown")
                      html_content += f"<p><b>{rule_id}</b> - {severity}<br>{message}</p>"
              html_content += "</body></html>"
              Path("codeql-report-${{ matrix.language }}.html").write_text(html_content)
          EOF
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-report-${{ matrix.language }}
          path: codeql-report-${{ matrix.language }}.html
  dependency-and-image-scan:
    name: Scan Dependencies & Docker Image
    runs-on: ubuntu-latest
    needs: analyze
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy -y
      - name: Scan Dependencies
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Build Docker image
        run: docker build -t myapp:latest -f Source/Functions/RPSLS.Python.Api/Dockerfile Source/Functions/RPSLS.Python.Api

      - name: Scan Docker image
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL myapp:latest

      - name: Generate Trivy Reports
        run: |
          trivy fs --format json --output trivy-dependencies-report.json .
          trivy image --format json --output trivy-docker-report.json myapp:latest
      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-reports
          path: |
            trivy-dependencies-report.json
            trivy-docker-report.json
