name: OWASP ZAP Dynamic Scan

on:
  push:
  pull_request:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up the application (for JavaScript or Python)
    - name: Set up Node.js (for JavaScript apps)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies (JavaScript)
      run: npm install

    - name: Set up Python (for Python apps)
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies (Python)
      run: pip install -r requirements.txt

    # Step 3: Start the application
    - name: Start the application
      run: |
        nohup npm start & # For JavaScript
        nohup python app.py & # For Python
        sleep 10 # Wait for the app to start

    # Step 4: Run OWASP ZAP Scan
    - name: Run OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: 'http://localhost:3000' # Replace with your app's URL
        #rules_file_name: '.zap/rules.json' # Optional: Custom rules
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
