name: CodeQL Analysis & Dependency/Image Scan

on:
  push:
  pull_request:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  
  dependency-and-image-scan:
    name: Analyse des dépendances (Trivy)
    runs-on: ubuntu-latest
    #needs: analyze
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy -y
      - name: Scan Dependencies
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Build Docker image
        run: docker build -t myapp:latest -f Source/Functions/RPSLS.Python.Api/Dockerfile Source/Functions/RPSLS.Python.Api

      - name: Scan Docker image
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL myapp:latest

      - name: Generate Trivy Reports
        run: |
          trivy fs --format json --output trivy-dependencies-report.json .
          trivy image --format json --output trivy-docker-report.json myapp:latest
      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-reports
          path: |
            trivy-dependencies-report.json
            trivy-docker-report.json
